# Usa una imagen base de Python
FROM python:3.9-slim

# directorio
WORKDIR /app

# copia de los archivos requeridos
COPY app.py app.py

# Instalar Flask
RUN pip install Flask

# puerto
EXPOSE 5000

# ejecucion la aplicación
CMD ["python", "app.py"]
